INSERT INTO tblStades (nom) VALUES 
('Camp Nou'),
('Parc des Princes'),
('DRV PNK Stadium'),
('Estadio Jose Alvalade'),
('Old Trafford'),
('Santiago Bernabeu'),
('Allianz Stadium'),
('Mrsool Park'),
('Stade Louis-II'),
('Estadio Urbano Caldeira (Vila Belmiro)'),
('Cegeka Arena'),
('Wohninvest Weserstadion'),
('Volkswagen Arena'),
('Stadion Miejski'),
('Signal Iduna Park'),
('Allianz Arena'),
('Celtic Park'),
('St Marys Stadium'),
('Anfield'),
('Estadio Ramon Sanchez Pizjuan'),
('St Jakob-Park'),
('Stamford Bridge'),
('Stadio Artemio Franchi'),
('Stadio Olimpico'),
('Groupama Stadium'),
('King Abdullah Sports City');

