INSERT INTO tblTitres (titre)
VALUES 
('Ballon dOr'),
('The Best Joueur de la FIFA'),
('Soulier dOr Europeen'),
('Prix Puskas de la FIFA'),
('Meilleur joueur UEFA'),
('Golden Boy'),
('Meilleur joueur de la Coupe du Monde FIFA'),
('Gant dOr de la Coupe du Monde FIFA'),
('Trophee Kopa'),
('Onze dOr'),
('Prix du Joueur de lAnnee PFA'),
('Prix du Joueur de lAnnee FWA'),
('Joueur africain de lannee CAF'),
('Meilleur joueur sud-americain de lannee'),
('Trophee Bravo'),
('Trophee Alfredo Di Stefano'),
('Joueur de lannee UEFA par poste'),
('Meilleur buteur dune competition'),
('Prix Golden Foot');
